### ISSUE TITLE
Please state AMQP compatibility

### ISSUE THREAD

**Issue by noncrab** [abhin4v/purescript-amqp#1]
This looks like a neat library. Although I notice one thing that could maybe help. As AMQP largely fractured when the AMQP 1 spec was released; it'd be great if you could explicitly state that (as with the underlying library) it uses AMQP 0.9.1, or is compatible with RabbitMQ.

The risk there is that you'll end with people wanting to use it with things like Qpid / ActiveMQ, and being disappointed when it doesn't work.

Cheers.

**Comment by abhin4v** [comment]
Done.
